[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alf_core"
version = "0.1.0"
description = "A Python package for performing active learning experiments."
readme = "README.md"
requires-python = ">=3.12,<3.14.1"
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "pydantic",
    "scipy>=1.9.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["alf_core*"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

# For testing pytorch-cpu is enough. If it's otherwise, replace the index
# with "pytorch-gpu"
[tool.uv.sources]
torch = { index = "pytorch-cpu" }
