[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alf_tools"
version = "0.1.0"
description = "A Python package with tools for performing active learning experiments."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alf_core",
    "requests>=2.25.0",
    "huggingface_hub==0.27.0",
    "jaxtyping>=0.3.5",
    "torch>=2.10.0",
    "gpytorch>=1.9.0",
    "scipy>=1.9.0",
    "rdkit>=2026.3.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["alf_tools*"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
alf_core = { path = "../core", editable = true }
torch = [
  { index = "pytorch-cpu" },
]
