[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alf_tools"
version = "0.1.0"
description = "A Python package with tools for performing active learning experiments."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alf_core",
    "requests>=2.25.0",
    "huggingface_hub==0.27.0",
    "jaxtyping>=0.3.5",
    "torch>=1.9.0",
    "gpytorch>=1.9.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["alf_tools*"]

[dependency-groups]
dev = [
    "pytest>=6.2.0",
    "pytest-cov>=2.12.0",
    "black>=21.0.0",
    "flake8>=3.9.0",
    "mypy>=0.910",
    "pre-commit>=4.1.0",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
alf_core = { path = "../core", editable = true }
torch = { index = "pytorch-cpu" }

[tool.uv]
default-groups = [
  "dev",
]
