# @package _global_
optimizer:
  acquisition_fn:
    _target_: alf_tools.optimizer.acquisition_functions.thompson_sampling.ThompsonSampling
  search_fn:
    _target_: alf_core.optimizer.search.DatasetSearch
