name: Tests and Linters 🧪

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linters:
    runs-on: instadeep-ci
    container:
      image: python:3.12-slim-bullseye

    steps:
      - name: Git setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout code  📦
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Lint
        run: |
          cd core && uv sync
          uv run --no-sync pre-commit run --all-files --verbose

  tests:
      runs-on: instadeep-ci-4
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      container:
        image: python:3.11-slim-bullseye

      steps:
        - name: Git setup
          run: |
            apt-get update && apt-get install -y \
            coreutils \
            git

        - name: Checkout code  📦
          uses: actions/checkout@v4
          with:
            fetch-depth: '0'

        - name: Add safe directory 🔒
          run: git config --system --add safe.directory $GITHUB_WORKSPACE

        - name: Install uv
          uses: astral-sh/setup-uv@v6

        - name: Run tests (core) 🧪
          run: |
            cd core
            uv sync
            uv run --no-sync pytest --verbose --cov-report xml:coverage-core.xml \
                            --cov-report term-missing \
                            --junitxml=pytest-core.xml \
                            --cov=alf_core

        - name: Run tests (tools) 🧪
          run: |
            cd tools
            uv sync
            uv run --no-sync pytest --verbose --cov-report xml:coverage-tools.xml \
                            --cov-report term-missing \
                            --junitxml=pytest-tools.xml \
                            --cov=alf_tools

        - name: Pytest coverage comment (core) 💬
          id: coverageCommentCore
          uses: MishaKav/pytest-coverage-comment@main
          with:
            title: Core Coverage Report
            unique-id-for-comment: coverage-core
            pytest-xml-coverage-path: core/coverage-core.xml
            junitxml-path: core/pytest-core.xml

        - name: Pytest coverage comment (tools) 💬
          id: coverageCommentTools
          uses: MishaKav/pytest-coverage-comment@main
          with:
            title: Tools Coverage Report
            unique-id-for-comment: coverage-tools
            pytest-xml-coverage-path: tools/coverage-tools.xml
            junitxml-path: tools/pytest-tools.xml
