name: Tests and Linters 🧪

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linters:
    runs-on: instadeep-ci
    container:
      image: python:3.12-slim-bullseye

    steps:
      - name: Git setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout code  📦
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Lint
        run: |
          cd core && uv sync --extra cpu
          uv run --no-sync pre-commit run --all-files --verbose

  tests:
      runs-on: instadeep-ci-4
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      container:
        image: python:3.11-slim-bullseye

      steps:
        - name: Git setup
          run: |
            apt-get update && apt-get install -y \
            coreutils \
            git

        - name: Checkout code  📦
          uses: actions/checkout@v4
          with:
            fetch-depth: '0'

        - name: Add safe directory 🔒
          run: git config --system --add safe.directory $GITHUB_WORKSPACE

        - name: Install uv
          uses: astral-sh/setup-uv@v6

        - name: Run tests (core) 🧪
          run: |
            mkdir -p reports
            cd core
            uv sync --extra cpu
            uv run --no-sync pytest --verbose \
                --cov=alf_core \
                --cov-report= \
                --junitxml=../reports/pytest-core.xml \
                --cov-report xml:../reports/coverage-core.xml

        - name: Run tests (tools) 🧪
          run: |
            cd tools
            uv sync --extra torch_cpu
            uv run --no-sync pytest --verbose \
                --cov=alf_tools \
                --cov-report= \
                --junitxml=../reports/pytest-tools.xml \
                --cov-report xml:../reports/coverage-tools.xml

        - name: Combine coverage files
          run: |
            pip install coverage junitparser
            coverage combine
            coverage xml -o coverage.xml

        - name: Merge JUnit reports
          run: |
            python - << 'EOF'
            from junitparser import JUnitXml
            core = JUnitXml.fromfile("reports/pytest-core.xml")
            tools = JUnitXml.fromfile("reports/pytest-tools.xml")

            merged = JUnitXml()
            merged.add_testsuite(core)
            merged.add_testsuite(tools)

            merged.write("reports/pytest-merged.xml")
            EOF

        - name: Pytest coverage 💬
          id: coverageComment
          uses: MishaKav/pytest-coverage-comment@main
          with:
            coverage-path: coverage.xml
            junitxml-path: reports/pytest-merged.xml
            title: Coverage
